version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    # - requirements: requirements.txt  # package requirements
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .
      # extra_requirements:
      #     - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
