name: tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py38
        - linux: py39
        - linux: py310
        - linux: py311
        - macos: py38
        - macos: py39
        - macos: py310
        - macos: py311
